### ISSUE TITLE
Providing data on a socket or pipe?

### ISSUE THREAD

**Issue by bmix** [argotronic/argus_data_api#4]
Would it be possible to provide the data in a more language agnostic way, like a socket or so?

**Comment by argotronic** [comment]
Argus Monitor is a hobby project, we (2 HW/SW engineers) work on in our spare time next to full time job and family. Time for this project is therefore rather limited.

Argus is written in C++ and this is the language we know best. We therefore decided to offer access to all our sensor data by means of shared memory, which should be supported by most other languages. We offer a C++ wrapper or accessor API as we know this language. But we gladly accept any other pull requests for APIs written in different languages.

We know of very few people using our data API, but not that many that would warrant investing any more of our time into developing this further. But as I have mentioned, anyone wanting to add another API for accessing the shared memory structure with the sensor data is welcome to submit a PR to this repo.
