### ISSUE TITLE
NZXT AIO Water Temp

### ISSUE THREAD

**Issue by iratemike** [argotronic/argus_data_api#6]
Hello,

I use Argus Monitor to control my NZXT Kraken X63 AIO pump speed and other fans based on water temp which Argus Monitor reports - however this doesn't seem to be surfaced by the API. I'm only raising this as a 'nice to have' 🙂.

Thanks again for the great software, and kind regards.

**Comment by argotronic** [comment]
Hi,

what sensor values are you missing exactly? I would expect the temperature, fan speed and fan control PWM values (in percent) to be all available via the data API.

**Comment by iratemike** [comment]
My apologies, the API is reporting the values. Initially I didn't realise as the label was "Temp 1" - after customising the label in Argus Monitor it became more clear.
